BIG-MAP/big-map-registry

apps.yaml

The DFT_VASP WaNo implements a wide range of methods available within the VASP code.

Add app DFT_VASP

---

apps.yaml

This is a new app that we want to add, which uses `ASE` technology to convert a geometry file from `x` to `y` format.

Format-Converter

---

apps.yaml

I’ve compiled a listing for the CLEASE GUI app (for BIG-MAP SI, CANADA project)
Adding a ping to @jinchang

Please add CLEASE GUI to the apps list

---

apps.yaml

This is the SEI Builder pre-release app developed by prof. Chivazzo team (PTD)

SEI Builder app

---

apps.yaml

This reverts commit ce220f41f5b39d2d392e56cece0aa333c717d122.

Revert "Add app HierCVAE (#48)"

---

README.md

Changed the incomplete acknowledgement phrase to match with the one provided by BIG-MAP [here](https://www.big-map.eu/dissemination/publications/acknowledgment)

Updated the acknowledgement phrase to BIG-MAP

---

apps.yaml

Based on EU meeting feedback, removed all the apps that were not compliant with the requirements. Fixed the minor issue of an app not showing the correct logo. Made a minor change to another app's name by dropping `app` from its name to make it more consistent with all other apps.

Removed the non-compliant apps from the appstore

---

apps.yaml

I update the yaml file where the apps are listed uncommenting my entry (hiercvae)  and replacing it with a new entry with the required fields (github link).

feat: updated yaml file for Hiercvae app

---

apps.yaml

BIG-MAP app to comply with the EU regulations

 electrolyte-screening

---

apps.yaml

update your BIG-MAP app to comply with the EU regulations

electrolyte-screening

---

apps.yaml

BIG-MAP app to comply with the EU regulations

dft-surface

---

apps.yaml

- feat: add nmrium information
- [pre-commit.ci] auto fixes from pre-commit.com hooks
- [pre-commit.ci] pre-commit autoupdate
- chore: update text
- [pre-commit.ci] auto fixes from pre-commit.com hooks
- [pre-commit.ci] pre-commit autoupdate
- [pre-commit.ci] pre-commit autoupdate
- [pre-commit.ci] pre-commit autoupdate
- add densityNEB app to registry
- [pre-commit.ci] pre-commit autoupdate
- add documentation_url to qm9-schnet-uncertainty app
- add git_url to qm9-schnet-uncertainty app
- fix git_url in qm9-schnet-uncertainty app
- Updated the acknowledgement phrase to BIG-MAP
- Update apps.yaml
- Update apps.yaml
- [pre-commit.ci] pre-commit autoupdate
- Fix app SEI Builder
- removed the non-compliant apps from the appstore
- added back aiidalab-qe which is now compliant with …

galvanicium

---

apps.yaml

Includes a new link for direct download of the installer files.
GitLab repo link moved to `git_url`.

New pull request FullProfAPP

---

apps.yaml

DARTS: add external URL to a server providing the service.

Update apps.yaml for "DARTS"

---

apps.yaml

Now the appstore hosts installation and demonstration video of aiidalab-auror, aiidalab-qe-app, densityneb, dft-qe, dft-vasp, electrolyte-screening and hiercvae

Added videos for various apps

---

apps.yaml

SDLabs App developed for the AutoProBe project led by the BIG-MAP partner DTU and external stakeholder Atinary Technologies. 
The project members are as follows:
* DTU: 
* Dr. Jinhyun Chang [jchang@dtu.dk](mailto:jchang@dtu.dk)
* Dr. Smobin Vincent [smvin@dtu.dk](mailto:smvin@dtu.dk)
* Nis Fisker-Bødker [nisfi@dtu.dk](mailto:nisfi@dtu.dk)
* Atinary Technologies:
* Dr. Loïc Roch [loic@atinary.com](mailto:loic@atinary.com)
* Daniel Pacheco [dpacheco@atinary.com](mailto:dpacheco@atinary.com)

Autonomous Optimization Protocol for Battery Electrolyte Development (AutoProBE)

---

apps.yaml

add onterface to apps.yaml

---

apps.yaml
schemas/metadata.schema.json
src/mod/templates/singlepage.html

Added videos for a few apps. Added option to display 1 video in case installation video is not required.
Added new keyword to check if the app is open source or not. This will be used to display closed source at the bottom of the page in a separate section.

Added videos and changed template

---

apps.yaml

Update description for quantum espresso app.

Update description for quantum espresso app

---

apps.yaml

Similar to the integration of the XAS app, This PR adds an entry point for the XPS app in the BIG-MAP app store.
We have released a new version of the AiiDAlab-QE App, so I also updated the version and state of the related app.

Add AiiDAlab-QE XAS App
